name: Build site

on:
  push:
    branches: [ beta ]
    paths-ignore:
      - '.github/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Inject access token in .npmrc
      run: | 
        echo "registry=https://npm.pkg.github.com/helsingborg-stad" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

    - name: Execute buildscripts in themes and plugins folders
      run: php ./build.php

    - name: Cleanup .npmrc
      run: rm ~/.npmrc

    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --backup --backup-dir=${{ secrets.DEPLOY_REMOTE_BACKUP_DIR_HELSINGBORG_SE }}
        path: .
        remote_path: ${{ secrets.DEPLOY_REMOTE_PATH_HELSINGBORG_SE }}
        remote_host: ${{ secrets.DEPLOY_REMOTE_HOST_HELSINGBORG_SE }}
        remote_user: ${{ secrets.DEPLOY_REMOTE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}